import { createSlice } from '@reduxjs/toolkit';
import mediaImport from '../../assets/mediaImports';

const initialState = {
    projects: [
        { id: 1, title: 'Bookstore CMS',
            description: `This is a Bookstore app built with HTML, CSS, REACT and Redux.\n\n Key features:\n   • Display a list of books\n   • Add a book\n   • Remove a selected book\n\nThe data is stored in a Redux store.`,
            stack: ['React', 'CSS', 'Javascript', 'NodeJS'], type: 'Front-end', github: 'https://github.com/anita00001/bookstore', demo: 'https://bookstore-pi-seven.vercel.app/', mediaPhoto: mediaImport.bookstoreImage,
            mediaVideo: mediaImport.featuredVideo 
        },
        { id: 2, title: 'Blog API 1', description: 'This project is an e-commerce platform designed to provide seamless shopping experiences for users. It integrates front-end, back-end, and database technologies. The platform features a fully responsive design, real-time inventory management, and secure payment gateways to ensure a top-notch user experience. This project is an e-commerce platform designed to provide seamless shopping experiences for users. It integrates front-end, back-end, and database technologies. The platform features a fully responsive design, real-time inventory management, and secure payment gateways to ensure a top-notch user experience.', stack: ['Ruby', 'PostgreSQL'], type: 'Back-end', github: '#', demo: '#', mediaPhoto: mediaImport.featuredImage, mediaVideo: mediaImport.featuredVideo },
        { id: 3, title: 'E-commerce Platform 1', description: 'This project is an e-commerce platform designed to provide seamless shopping experiences for users. It integrates front-end, back-end, and database technologies. The platform features a fully responsive design, real-time inventory management, and secure payment gateways to ensure a top-notch user experience. This project is an e-commerce platform designed to provide seamless shopping experiences for users. It integrates front-end, back-end, and database technologies. The platform features a fully responsive design, real-time inventory management, and secure payment gateways to ensure a top-notch user experience.', stack: ['React/Redux', 'Ruby on Rails'], type: 'Full Stack', github: '#', demo: '#', mediaPhoto: mediaImport.featuredImage, mediaVideo: mediaImport.featuredVideo },
        { id: 4, title: 'Task Manager 1', description: 'This project is an e-commerce platform designed to provide seamless shopping experiences for users. It integrates front-end, back-end, and database technologies. The platform features a fully responsive design, real-time inventory management, and secure payment gateways to ensure a top-notch user experience. This project is an e-commerce platform designed to provide seamless shopping experiences for users. It integrates front-end, back-end, and database technologies. The platform features a fully responsive design, real-time inventory management, and secure payment gateways to ensure a top-notch user experience.', stack: ['React', 'Node.js'], type: 'Full Stack', github: '#', demo: '#', mediaPhoto: mediaImport.featuredImage, mediaVideo: mediaImport.featuredVideo },
        { id: 5, title: 'Math Magician', description: 'This is a math magicians app built with HTML, CSS, REACT. In this app you can make some calculations math like the addition, subtraction, multiplication and division. \n The external API is used to fetch random quotes for the app using the use effect hook.', stack: ['React', 'React Hooks', 'CSS'], type: 'Front-end', github: 'https://github.com/anita00001/math_magicians', demo: 'https://math-magicians-8o2g.onrender.com/', mediaPhoto: mediaImport.mathMagicianImage, mediaVideo: mediaImport.featuredVideo },
        { id: 6, title: 'To Do List App', description: 'This a Todos app built with HTML, CSS and REACT. In this app you can create and manage the Todos list like - \n * adding Todos,\n * Marking completed Todos,\n * deleting a completed Todos,\n * Clearing all completed Todos\n\n We have implemented the props, event handling like onClick and Hooks like useState and useEffect.', stack: ['HTML/CSS', 'React', 'React useState', 'React useEffect'], type: 'Front-end', github: 'https://github.com/anita00001/react-todos', demo: 'https://todo-app-anita.vercel.app/', mediaPhoto: mediaImport.toDoImage, mediaVideo: mediaImport.featuredVideo },
        { id: 7, title: 'Blog API 2', description: 'This project is an e-commerce platform designed to provide seamless shopping experiences for users. It integrates front-end, back-end, and database technologies. The platform features a fully responsive design, real-time inventory management, and secure payment gateways to ensure a top-notch user experience. This project is an e-commerce platform designed to provide seamless shopping experiences for users. It integrates front-end, back-end, and database technologies. The platform features a fully responsive design, real-time inventory management, and secure payment gateways to ensure a top-notch user experience.', stack: ['Ruby', 'PostgreSQL'], type: 'Back-end', github: '#', demo: '#', mediaPhoto: mediaImport.featuredImage, mediaVideo: mediaImport.featuredVideo },
        { id: 8, title: 'E-commerce Platform 2', description: 'This project is an e-commerce platform designed to provide seamless shopping experiences for users. It integrates front-end, back-end, and database technologies. The platform features a fully responsive design, real-time inventory management, and secure payment gateways to ensure a top-notch user experience. This project is an e-commerce platform designed to provide seamless shopping experiences for users. It integrates front-end, back-end, and database technologies. The platform features a fully responsive design, real-time inventory management, and secure payment gateways to ensure a top-notch user experience.', stack: ['React/Redux', 'Ruby on Rails'], type: 'Full Stack', github: '#', demo: '#', mediaPhoto: mediaImport.featuredImage, mediaVideo: mediaImport.featuredVideo },
        { id: 9, title: 'Task Manager 2', description: 'This project is an e-commerce platform designed to provide seamless shopping experiences for users. It integrates front-end, back-end, and database technologies. The platform features a fully responsive design, real-time inventory management, and secure payment gateways to ensure a top-notch user experience. This project is an e-commerce platform designed to provide seamless shopping experiences for users. It integrates front-end, back-end, and database technologies. The platform features a fully responsive design, real-time inventory management, and secure payment gateways to ensure a top-notch user experience.', stack: ['React', 'Node.js'], type: 'Full Stack', github: '#', demo: '#', mediaPhoto: mediaImport.featuredImage, mediaVideo: mediaImport.featuredVideo },
        { id: 10, title: 'Art Gallery', description: 'This project is a JavaScript project - API-based webapp, using webpack and ES6 features, notably modules.\n\n Key features - \n * Use callbacks and promises \n * Use ES6 modules to write modular JavaScript \n * Use webpack to bundle JavaScript.', stack: ['HTML', 'CSS', 'JavaScript ES6', 'NodeJS', 'Webpack'], type: 'Front-end', github: 'https://github.com/anita00001/js-capstone', demo: 'https://dev-mamun.github.io/Art-Gallery/dist/#', mediaPhoto: mediaImport.ArtGalleryImage, mediaVideo: mediaImport.featuredVideo },
        { id: 11, title: 'Space Travellers Hub', description: 'This is a Space Travelers application developed by using REACT. The app serves as a platform for reserving rockets and joining missions, offering a diverse range of functionalities through API calls.\n\n Key features - \n * User can Reserve Rockets \n * User can join Missions \n * User can view reserved rockets and joined mission on My Profile \n', stack: ['React', 'CSS', 'Javascript', 'NodeJS'], type: 'Front-end', github: 'https://github.com/anita00001/space-traveller-hub', demo: 'https://space-travellers-hub-uw83.onrender.com/', mediaPhoto: mediaImport.SpaceTravellersHubImage, mediaVideo: mediaImport.featuredVideo },
        { id: 12, title: 'Blog API 3', description: 'This project is an e-commerce platform designed to provide seamless shopping experiences for users. It integrates front-end, back-end, and database technologies. The platform features a fully responsive design, real-time inventory management, and secure payment gateways to ensure a top-notch user experience. This project is an e-commerce platform designed to provide seamless shopping experiences for users. It integrates front-end, back-end, and database technologies. The platform features a fully responsive design, real-time inventory management, and secure payment gateways to ensure a top-notch user experience.', stack: ['Ruby', 'PostgreSQL'], type: 'Back-end', github: '#', demo: '#', mediaPhoto: mediaImport.featuredImage, mediaVideo: mediaImport.featuredVideo },
        { id: 13, title: 'E-commerce Platform 3', description: 'This project is an e-commerce platform designed to provide seamless shopping experiences for users. It integrates front-end, back-end, and database technologies. The platform features a fully responsive design, real-time inventory management, and secure payment gateways to ensure a top-notch user experience. This project is an e-commerce platform designed to provide seamless shopping experiences for users. It integrates front-end, back-end, and database technologies. The platform features a fully responsive design, real-time inventory management, and secure payment gateways to ensure a top-notch user experience.', stack: ['React/Redux', 'Ruby on Rails'], type: 'Full Stack', github: '#', demo: '#', mediaPhoto: mediaImport.featuredImage, mediaVideo: mediaImport.featuredVideo },
        { id: 14, title: 'Task Manager 3', description: 'This project is an e-commerce platform designed to provide seamless shopping experiences for users. It integrates front-end, back-end, and database technologies. The platform features a fully responsive design, real-time inventory management, and secure payment gateways to ensure a top-notch user experience. This project is an e-commerce platform designed to provide seamless shopping experiences for users. It integrates front-end, back-end, and database technologies. The platform features a fully responsive design, real-time inventory management, and secure payment gateways to ensure a top-notch user experience.', stack: ['React', 'Node.js'], type: 'Full Stack', github: '#', demo: '#', mediaPhoto: mediaImport.featuredImage, mediaVideo: mediaImport.featuredVideo },
        { id: 15, title: 'Exhibition Page', description: 'The technical Exhibition page includes event details about the engineering projects, allowing participants to register for the competition. Built with HTML, CSS and JavaScript.', stack: ['HTML', 'CSS', 'Javascript'], type: 'Front-end', github: 'https://github.com/anita00001/Exhibition-Page', demo: 'https://anita00001.github.io/Exhibition-Page/', mediaPhoto: mediaImport.ExhibitionImage, mediaVideo: mediaImport.featuredVideo },
    ],
    filter: 'Full Stack',
    showAllFullStack: false,
    showAllProjects: false,
};

const projectSlice = createSlice({
    name: 'projects',
    initialState,
    reducers: {
        setFilter: (state, action) => {
            state.filter = action.payload;
            state.showAllFullStack = false;
            state.showAllProjects = false;
        },
        toggleFullStack: (state) => {
            state.showAllFullStack = !state.showAllFullStack;
        },
        toggleAllProjects: (state) => {
            state.showAllProjects = true;
        },
    },
});

export const { setFilter, toggleFullStack, toggleAllProjects } = projectSlice.actions;
export default projectSlice.reducer;
